### ISSUE TITLE
Breadcrumbs fails to extend to blog posts

### ISSUE THREAD

**Issue by kaleeraisor** [Bixie/pagekit-breadcrumbs#2]
When viewing a blog post the breadcrumb should extend to the post and the blog page should be linked but it doesn't seem to recognize it.

For example you can view here at the bottom:
[http://piebay.com/blog/hello-pagekit](http://piebay.com/blog/hello-pagekit)

**Comment by malles** [comment]
That would have to be done by the extension, Blog in this case, as described in the README file of this repo. 
I may want to try to render blog crumbs if possible.

**Comment by malles** [comment]
I could hook into the view quite easily. Thanks for the tip.
