### ISSUE TITLE
No breadcrumb shown on own extension

### ISSUE THREAD

**Issue by ahoiroman** [Bixie/pagekit-breadcrumbs#3]
Hello,

I created my own little extension with a small frontend view. Unfortunately this is not "recognized" by the breadcrumbs-widget. The module position is empty, if I open the extension, which is linked in the main menu.

Do I have to "register" the extension somehow to the breadcrumbs?

**Comment by malles** [comment]
The breadcrumbs module should always show the active menu path. If you want to have the breadcrumbs show sub-items of your extension, you can add them with the code shown in the readme of this repo.
